---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
  env:
    ANSIBLE_ROLES_PATH: ../shared

driver:
  name: docker

platforms:
  - name: ansible-role-tigervnc-debian-11
    image: debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-tigervnc-debian-12
    image: debian:12
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-tigervnc-ubuntu-2004
    image: ubuntu:20.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: ansible-role-tigervnc-ubuntu-2204
    image: ubuntu:22.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible

verifier:
  name: testinfra
